### PR TITLE
Support for unknown enum values

### PR DESCRIPTION
**Pull request by hoeschele-consistec**
Our company is migrating our implementation from using Java protobuf to Scalapb. 
We rely on JSON serialization and deserialization for tests and communication with elasticsearch.

Our problem:
The Java protobuf JSON IO implementation supports printing and parsing unknown enum values.

scalapb-json4s will throw a JsonFormatException when presented with unknown numeric enum values. When serializing a GeneratedMessage containing unknown numeric enum values these are not serialized as number.

Our solution:
I added support for parsing and printing unknown numeric enum values, configurable with a new config option that defaults to preserve the current behavior. Without explicitly enabling the handling of unknown enum values this does not impact current users but offers users an option to get the same behavior that is the default in the standard Java implementation. Feel free to change the names of the config options. I think it would be worthwhile to merge this upstream because other people could benefit from this and we would not need to maintain our own fork in the future.

Cheers,

Matthias Höschele

### CODE REVIEW

**Comment by hoeschele-consistec** [comment]
@thesamet Could you please have a look at this small merge request? The failing check looks simply like an oversensitivity of MiMa that complains about different types of synthetic methods that are only called internally and genereated by the compiler.

**Comment by thesamet** [comment]
Sorry for the delay -  I missed the notification for the original pull request. Looks good.
- Can you add unit tests for the new flag? 
- Can you make sure the default value for the new flags are equivalent to the default behavior of the official Java version? (I'm ok with breaking compatibility between ScalaPB versions for unknown enums for the sake of consistency with the Java behavior)

**Comment by hoeschele-consistec** [comment]
>     * Can you make sure the default value for the new flags are equivalent to the default behavior of the official Java version? (I'm ok with breaking compatibility between ScalaPB versions for unknown enums for the sake of consistency with the Java behavior)
In my initial pull request I was rather conservative and prioritized compatibility with previous ScalaPB versions because some people might rely on the JsonFormatException that is currently thrown in the case of unknown numeric enum values and we might silently give them unexpected values instead.

Concerning the question of default behavior in Java Protobuf:
https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1108
For the Java Protobuf implementation of the printer the default behavior is equivalent to the new flag being set to true.


https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1749
For the Java Protobuf implementation of the parser the default behavior for proto3 syntax is equivalent to the new flag being set to true, in all other cases it is equivalent to the new flag being set to false.
So to have proper behavioral equivalence to Java Protobuf the flag should be set to true by default and only apply in case of proto3 syntax.

Since semantics on parser side are more complicated and have more repercussions please let me know how you would like this to be configurable and what the default behavior should be. Based on that I'll adjust the changes and will add the appropriate unit tests.

**Comment by hoeschele-consistec** [comment]
@thesamet regarding the default behavior of the official Java version:

https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1108
The printer behaves as is the new flag is enabled.

https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1749
The parser behaves like the new flag is enabled for proto3 syntax and like the new flag is disabled for all other cases. Current users of scalapb-json4s might rely on its current behavior of throwing a JsonFormatException on seeing unknown enum values. To by default silently return unexpected values seemed risky to me and therefore the flag is disabled by default in my pull request.

I think as a maintainer this is your call, so please let me know how you would like this to be configurable and what should be the default behavior and I'll adapt my changes accordingly and I'll add appropriate unit tests.

**Comment by hoeschele-consistec** [comment]
@thesamet regarding the default behavior of the official Java version:

https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1108
The printer behaves as is the new flag is enabled.

https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1749
The parser behaves like the new flag is enabled for proto3 syntax and like the new flag is disabled for all other cases. Current users of scalapb-json4s might rely on its current behavior of throwing a JsonFormatException on seeing unknown enum values. To by default silently return unexpected values seemed risky to me and therefore the flag is disabled by default in my pull request.

I think as a maintainer this is your call, so please let me know how you would like this to be configurable and what should be the default behavior and I'll adapt my changes accordingly and I'll add appropriate unit tests.

**Comment by hoeschele-consistec** [comment]
@thesamet regarding the default behavior of the official Java version:

https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1108
The printer behaves as is the new flag is enabled.

https://github.com/protocolbuffers/protobuf/blob/565c26e7a1855c4139e288daa9c50aa6da4c9f3a/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L1749
The parser behaves like the new flag is enabled for proto3 syntax and like the new flag is disabled for all other cases. Current users of scalapb-json4s might rely on its current behavior of throwing a JsonFormatException on seeing unknown enum values. To by default silently return unexpected values seemed risky to me and therefore the flag is disabled by default in my pull request.

I think as a maintainer this is your call, so please let me know how you would like this to be configurable and what should be the default behavior and I'll adapt my changes accordingly and I'll add appropriate unit tests.

**Comment by thesamet** [comment]
@hoeschele-consistec thanks for looking into this.

For the printer, make the flag named `formattingEnumsAsInt` with default `false`. To match the Java behavior an enum would be printed as a number if and only if this flag is true OR it's an unrecognized enum.

For the parser, for now, let's mimic the Java behavior without introducing a new flag. I'm not sure why they make the distinction between proto2 and proto3, but let's follow that.

**Comment by thesamet** [comment]
Thanks for the PR. I recently merged a changed that matches enum handled to the java protobuf (see `ignoreUnknownFields` option.

**Pull request closed without merging**
